version: '3.9'

services:
  
  training-service-db:
    image: postgis/postgis:latest
    container_name: training-service-db
    environment:
      - POSTGRES_DB=training-service
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
    ports:
      - "5400:5432"
    volumes:
      - training-service-db:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U test -d training-service'" ]
      interval: 10s
      timeout: 3s
      retries: 3

  zookeeper:
    image: 'confluentinc/cp-zookeeper:7.3.2'
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_SERVER_ID: '1'
      ZOOKEEPER_SERVERS: 'zookeeper:2888:3888'
      ZOOKEEPER_CLIENT_PORT: '2181'
      ZOOKEEPER_PEER_PORT: '2888'
      ZOOKEEPER_LEADER_PORT: '3888'
      ZOOKEEPER_INIT_LIMIT: '10'
      ZOOKEEPER_SYNC_LIMIT: '5'
      ZOOKEEPER_MAX_CLIENT_CONNS: '5'
    
  broker-1:
    image: 'confluentinc/cp-kafka:7.3.2'
    container_name: broker-1
    depends_on:
      - zookeeper
    ports:
      - "29091:29091"
    environment:
      KAFKA_BROKER_ID: '1'
      KAFKA_BROKER_RACK: '1'
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENERS: 'LISTENER_INTERNAL://:9091,LISTENER_LOCAL://:29091'
      KAFKA_ADVERTISED_LISTENERS: 'LISTENER_INTERNAL://broker-1:9091,LISTENER_LOCAL://localhost:29091'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'LISTENER_INTERNAL'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'LISTENER_INTERNAL:PLAINTEXT,LISTENER_LOCAL:PLAINTEXT'
      KAFKA_DEFAULT_REPLICATION_FACTOR: '1'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: '1'
      
  broker-2:
    image: 'confluentinc/cp-kafka:7.3.2'
    container_name: broker-2
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: '2'
      KAFKA_BROKER_RACK: '2'
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENERS: 'LISTENER_INTERNAL://:9091,LISTENER_LOCAL://:29092'
      KAFKA_ADVERTISED_LISTENERS: 'LISTENER_INTERNAL://broker-2:9091,LISTENER_LOCAL://localhost:29092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'LISTENER_INTERNAL'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'LISTENER_INTERNAL:PLAINTEXT,LISTENER_LOCAL:PLAINTEXT'
      KAFKA_DEFAULT_REPLICATION_FACTOR: '1'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: '1'

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - 29094:8080
    environment:
      - KAFKA_CLUSTERS_0_NAME=kostromaski
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=broker-1:9091
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181

volumes:
  training-service-db:
    name: training-service-db