// <auto-generated />
using System;
using Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(TrainingDbContext))]
    partial class TrainingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Model.Subscription", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigserial");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnType("geometry(Point,4326)")
                        .HasColumnName("location");

                    b.Property<int>("Radius")
                        .HasColumnType("integer")
                        .HasColumnName("radius");

                    b.Property<int?>("SubTypeId")
                        .HasColumnType("integer");

                    b.Property<long>("SubscriberId")
                        .HasColumnType("bigint");

                    b.Property<int?>("TypeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SubTypeId");

                    b.HasIndex("SubscriberId");

                    b.HasIndex("TypeId");

                    b.ToTable("Subscriptions", "training");
                });

            modelBuilder.Entity("Domain.Model.Training", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigserial");

                    b.Property<long>("AuthorId")
                        .HasColumnType("bigint");

                    b.Property<double>("AverageSpeed")
                        .HasColumnType("decimal")
                        .HasColumnName("averageSpeed");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdAt");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("onDate");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("description");

                    b.Property<int>("Distance")
                        .HasColumnType("integer")
                        .HasColumnName("distance");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Point>("StartPoint")
                        .IsRequired()
                        .HasColumnType("geometry(Point,4326)")
                        .HasColumnName("startPoint");

                    b.Property<DateTimeOffset>("Time")
                        .HasColumnType("time with time zone")
                        .HasColumnName("onTime");

                    b.Property<int>("TrainingTypeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("TrainingTypeId");

                    b.ToTable("Trainings", "training");
                });

            modelBuilder.Entity("Domain.Model.TrainingSubType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("TrainingTypeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TrainingTypeId");

                    b.ToTable("TrainingSubTypes", "training");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Шоссе",
                            TrainingTypeId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Трейл",
                            TrainingTypeId = 1
                        },
                        new
                        {
                            Id = 3,
                            Name = "Шоссе",
                            TrainingTypeId = 2
                        },
                        new
                        {
                            Id = 4,
                            Name = "MTB",
                            TrainingTypeId = 2
                        },
                        new
                        {
                            Id = 5,
                            Name = "Классический стиль",
                            TrainingTypeId = 3
                        },
                        new
                        {
                            Id = 6,
                            Name = "Свободный стиль",
                            TrainingTypeId = 3
                        },
                        new
                        {
                            Id = 7,
                            Name = "Лыжероллеры",
                            TrainingTypeId = 3
                        },
                        new
                        {
                            Id = 8,
                            Name = "Бассейн",
                            TrainingTypeId = 4
                        },
                        new
                        {
                            Id = 9,
                            Name = "Открытая вода",
                            TrainingTypeId = 4
                        });
                });

            modelBuilder.Entity("Domain.Model.TrainingType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("TrainingTypes", "training");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Бег"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Велоспорт"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Беговые лыжи"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Плавание"
                        });
                });

            modelBuilder.Entity("Domain.Model.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("TelegramId")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("Users", "training");
                });

            modelBuilder.Entity("Domain.Model.Subscription", b =>
                {
                    b.HasOne("Domain.Model.TrainingSubType", "SubType")
                        .WithMany()
                        .HasForeignKey("SubTypeId");

                    b.HasOne("Domain.Model.User", "Subscriber")
                        .WithMany()
                        .HasForeignKey("SubscriberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Model.TrainingType", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId");

                    b.Navigation("SubType");

                    b.Navigation("Subscriber");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("Domain.Model.Training", b =>
                {
                    b.HasOne("Domain.Model.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Model.TrainingSubType", "TrainingType")
                        .WithMany()
                        .HasForeignKey("TrainingTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("TrainingType");
                });

            modelBuilder.Entity("Domain.Model.TrainingSubType", b =>
                {
                    b.HasOne("Domain.Model.TrainingType", "TrainingType")
                        .WithMany()
                        .HasForeignKey("TrainingTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TrainingType");
                });
#pragma warning restore 612, 618
        }
    }
}
